title: Visualalgo
email: your-email@example.com
description: ""
destination: docs
baseurl: ""
# baseurl: "/visualalgo-design"
url: ""
twitter_username: jekyllrb
github_username:  jekyll

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
